- name: Check if user is lingering
  stat:
    path: '/var/lib/systemd/linger/{{ user.name }}'
  register: user_lingering

- name: Enable lingering is needed
  command: 'loginctl enable-linger {{ user.name }}'
  when: not user_lingering.stat.exists
